export type ProductBase = {
  id: string;
  codigoProduto: string;
  nome: string;
  descricao: string;
  unidadeMedida: string;
  pesoUnitario: number;
  categoria: string;
  temperaturaIdeal: string;
  status: string;
};

export const mockProductBase: ProductBase[] = [
  {
    id: "1",
    codigoProduto: "12345",
    nome: "Arroz Branco Tipo 1",
    descricao: "Arroz Branco Tipo 1 - 5kg",
    unidadeMedida: "kg",
    pesoUnitario: 5,
    categoria: "Alimentos Secos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "2",
    codigoProduto: "67890",
    nome: "Feijão Carioca",
    descricao: "Feijão Carioca - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Alimentos Secos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "3",
    codigoProduto: "11223",
    nome: "Leite Integral UHT",
    descricao: "Leite Integral UHT - 1L",
    unidadeMedida: "L",
    pesoUnitario: 1,
    categoria: "Laticínios",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "4",
    codigoProduto: "44556",
    nome: "Óleo de Soja Refinado",
    descricao: "Óleo de Soja Refinado - 900ml",
    unidadeMedida: "ml",
    pesoUnitario: 900,
    categoria: "Óleos e Gorduras",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "5",
    codigoProduto: "77889",
    nome: "Açúcar Refinado",
    descricao: "Açúcar Refinado - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Alimentos Secos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "6",
    codigoProduto: "99001",
    nome: "Café Torrado e Moído",
    descricao: "Café Torrado e Moído - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Bebidas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "7",
    codigoProduto: "22334",
    nome: "Macarrão Espaguete",
    descricao: "Macarrão Espaguete - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Massas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "8",
    codigoProduto: "55667",
    nome: "Biscoito Cream Cracker",
    descricao: "Biscoito Cream Cracker - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Biscoitos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "9",
    codigoProduto: "88990",
    nome: "Sabão em Pó",
    descricao: "Sabão em Pó - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Limpeza",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "10",
    codigoProduto: "33445",
    nome: "Shampoo Anticaspa",
    descricao: "Shampoo Anticaspa - 400ml",
    unidadeMedida: "ml",
    pesoUnitario: 400,
    categoria: "Higiene Pessoal",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "11",
    codigoProduto: "578150",
    nome: "Refrigerante Cola",
    descricao: "Refrigerante Cola - 2L",
    unidadeMedida: "L",
    pesoUnitario: 2,
    categoria: "Bebidas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "12",
    codigoProduto: "100001",
    nome: "Cerveja Pilsen Lata",
    descricao: "Cerveja Pilsen Lata - 350ml",
    unidadeMedida: "ml",
    pesoUnitario: 350,
    categoria: "Bebidas Alcoólicas",
    temperaturaIdeal: "Frio",
    status: "Ativo"
  },
  {
    id: "13",
    codigoProduto: "100002",
    nome: "Chocolate ao Leite Barra",
    descricao: "Chocolate ao Leite Barra - 90g",
    unidadeMedida: "g",
    pesoUnitario: 90,
    categoria: "Doces e Sobremesas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "14",
    codigoProduto: "100003",
    nome: "Pão de Forma Tradicional",
    descricao: "Pão de Forma Tradicional - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Panificação",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "15",
    codigoProduto: "100004",
    nome: "Queijo Mussarela Fatiado",
    descricao: "Queijo Mussarela Fatiado - 150g",
    unidadeMedida: "g",
    pesoUnitario: 150,
    categoria: "Laticínios",
    temperaturaIdeal: "Resfriado",
    status: "Ativo"
  },
  {
    id: "16",
    codigoProduto: "100005",
    nome: "Presunto Cozido Fatiado",
    descricao: "Presunto Cozido Fatiado - 180g",
    unidadeMedida: "g",
    pesoUnitario: 180,
    categoria: "Frios e Embutidos",
    temperaturaIdeal: "Resfriado",
    status: "Ativo"
  },
  {
    id: "17",
    codigoProduto: "100006",
    nome: "Iogurte Natural Integral",
    descricao: "Iogurte Natural Integral - 170g",
    unidadeMedida: "g",
    pesoUnitario: 170,
    categoria: "Laticínios",
    temperaturaIdeal: "Resfriado",
    status: "Ativo"
  },
  {
    id: "18",
    codigoProduto: "100007",
    nome: "Água Mineral sem Gás",
    descricao: "Água Mineral sem Gás - 1.5L",
    unidadeMedida: "L",
    pesoUnitario: 1.5,
    categoria: "Bebidas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "19",
    codigoProduto: "100008",
    nome: "Salsicha Congelada",
    descricao: "Salsicha Congelada - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "20",
    codigoProduto: "100009",
    nome: "Pizza Congelada Calabresa",
    descricao: "Pizza Congelada Calabresa - 400g",
    unidadeMedida: "g",
    pesoUnitario: 400,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "21",
    codigoProduto: "100010",
    nome: "Sorvete de Creme",
    descricao: "Sorvete de Creme - 1L",
    unidadeMedida: "L",
    pesoUnitario: 1,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "22",
    codigoProduto: "100011",
    nome: "Batata Frita Congelada",
    descricao: "Batata Frita Congelada - 700g",
    unidadeMedida: "g",
    pesoUnitario: 700,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "23",
    codigoProduto: "100012",
    nome: "Carne Moída Congelada",
    descricao: "Carne Moída Congelada - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "24",
    codigoProduto: "100013",
    nome: "Frango Congelado a Passarinho",
    descricao: "Frango Congelado a Passarinho - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "25",
    codigoProduto: "100014",
    nome: "Peixe Congelado Filé de Tilápia",
    descricao: "Peixe Congelado Filé de Tilápia - 400g",
    unidadeMedida: "g",
    pesoUnitario: 400,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "26",
    codigoProduto: "100015",
    nome: "Vegetais Congelados Mix",
    descricao: "Vegetais Congelados Mix - 300g",
    unidadeMedida: "g",
    pesoUnitario: 300,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "27",
    codigoProduto: "100016",
    nome: "Pão de Queijo Congelado",
    descricao: "Pão de Queijo Congelado - 400g",
    unidadeMedida: "g",
    pesoUnitario: 400,
    categoria: "Congelados",
    temperaturaIdeal: "Congelado",
    status: "Ativo"
  },
  {
    id: "28",
    codigoProduto: "100017",
    nome: "Suco Concentrado Laranja",
    descricao: "Suco Concentrado Laranja - 500ml",
    unidadeMedida: "ml",
    pesoUnitario: 500,
    categoria: "Bebidas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "29",
    codigoProduto: "100018",
    nome: "Molho de Tomate Tradicional",
    descricao: "Molho de Tomate Tradicional - 340g",
    unidadeMedida: "g",
    pesoUnitario: 340,
    categoria: "Mercearia",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "30",
    codigoProduto: "100019",
    nome: "Atum Sólido em Óleo",
    descricao: "Atum Sólido em Óleo - 170g",
    unidadeMedida: "g",
    pesoUnitario: 170,
    categoria: "Enlatados",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "31",
    codigoProduto: "100020",
    nome: "Milho Verde em Conserva",
    descricao: "Milho Verde em Conserva - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Enlatados",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "32",
    codigoProduto: "100021",
    nome: "Ervilha em Conserva",
    descricao: "Ervilha em Conserva - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Enlatados",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "33",
    codigoProduto: "100022",
    nome: "Azeitona Verde sem Caroço",
    descricao: "Azeitona Verde sem Caroço - 100g",
    unidadeMedida: "g",
    pesoUnitario: 100,
    categoria: "Mercearia",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "34",
    codigoProduto: "100023",
    nome: "Maionese Tradicional",
    descricao: "Maionese Tradicional - 250g",
    unidadeMedida: "g",
    pesoUnitario: 250,
    categoria: "Condimentos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "35",
    codigoProduto: "100024",
    nome: "Ketchup Tradicional",
    descricao: "Ketchup Tradicional - 400g",
    unidadeMedida: "g",
    pesoUnitario: 400,
    categoria: "Condimentos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "36",
    codigoProduto: "100025",
    nome: "Mostarda Amarela",
    descricao: "Mostarda Amarela - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Condimentos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "37",
    codigoProduto: "100026",
    nome: "Sal Refinado",
    descricao: "Sal Refinado - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Temperos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "38",
    codigoProduto: "100027",
    nome: "Pimenta do Reino Moída",
    descricao: "Pimenta do Reino Moída - 50g",
    unidadeMedida: "g",
    pesoUnitario: 50,
    categoria: "Temperos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "39",
    codigoProduto: "100028",
    nome: "Vinagre de Álcool",
    descricao: "Vinagre de Álcool - 750ml",
    unidadeMedida: "ml",
    pesoUnitario: 750,
    categoria: "Condimentos",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "40",
    codigoProduto: "100029",
    nome: "Azeite de Oliva Extra Virgem",
    descricao: "Azeite de Oliva Extra Virgem - 500ml",
    unidadeMedida: "ml",
    pesoUnitario: 500,
    categoria: "Óleos e Gorduras",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "41",
    codigoProduto: "100030",
    nome: "Manteiga com Sal",
    descricao: "Manteiga com Sal - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Laticínios",
    temperaturaIdeal: "Frio",
    status: "Ativo"
  },
  {
    id: "42",
    codigoProduto: "100031",
    nome: "Margarina Cremosa",
    descricao: "Margarina Cremosa - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Óleos e Gorduras",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "43",
    codigoProduto: "100032",
    nome: "Ovos Brancos Grandes",
    descricao: "Ovos Brancos Grandes - Dúzia",
    unidadeMedida: "Dúzia",
    pesoUnitario: 1,
    categoria: "Perecíveis",
    temperaturaIdeal: "Frio",
    status: "Ativo"
  },
  {
    id: "44",
    codigoProduto: "100033",
    nome: "Cebola Roxa",
    descricao: "Cebola Roxa - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "45",
    codigoProduto: "100034",
    nome: "Alho Branco",
    descricao: "Alho Branco - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "46",
    codigoProduto: "100035",
    nome: "Batata Inglesa",
    descricao: "Batata Inglesa - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "47",
    codigoProduto: "100036",
    nome: "Tomate Salada",
    descricao: "Tomate Salada - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "48",
    codigoProduto: "100037",
    nome: "Alface Crespa",
    descricao: "Alface Crespa - Unidade",
    unidadeMedida: "Unidade",
    pesoUnitario: 1,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "49",
    codigoProduto: "100038",
    nome: "Banana Prata",
    descricao: "Banana Prata - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "50",
    codigoProduto: "100039",
    nome: "Maçã Fuji",
    descricao: "Maçã Fuji - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "51",
    codigoProduto: "100040",
    nome: "Laranja Pera",
    descricao: "Laranja Pera - 1kg",
    unidadeMedida: "kg",
    pesoUnitario: 1,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "52",
    codigoProduto: "100041",
    nome: "Limão Tahiti",
    descricao: "Limão Tahiti - 500g",
    unidadeMedida: "g",
    pesoUnitario: 500,
    categoria: "Hortifruti",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "53",
    codigoProduto: "100042",
    nome: "Pão Francês",
    descricao: "Pão Francês - Unidade",
    unidadeMedida: "Unidade",
    pesoUnitario: 1,
    categoria: "Panificação",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "54",
    codigoProduto: "100043",
    nome: "Bolo de Chocolate Pronto",
    descricao: "Bolo de Chocolate Pronto - 300g",
    unidadeMedida: "g",
    pesoUnitario: 300,
    categoria: "Doces e Sobremesas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "55",
    codigoProduto: "100044",
    nome: "Pudim de Leite Pronto",
    descricao: "Pudim de Leite Pronto - 150g",
    unidadeMedida: "g",
    pesoUnitario: 150,
    categoria: "Doces e Sobremesas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "56",
    codigoProduto: "100045",
    nome: "Gelatina em Pó Morango",
    descricao: "Gelatina em Pó Morango - 20g",
    unidadeMedida: "g",
    pesoUnitario: 20,
    categoria: "Doces e Sobremesas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "57",
    codigoProduto: "100046",
    nome: "Creme de Leite UHT",
    descricao: "Creme de Leite UHT - 200g",
    unidadeMedida: "g",
    pesoUnitario: 200,
    categoria: "Laticínios",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "58",
    codigoProduto: "100047",
    nome: "Leite Condensado",
    descricao: "Leite Condensado - 395g",
    unidadeMedida: "g",
    pesoUnitario: 395,
    categoria: "Laticínios",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "59",
    codigoProduto: "100048",
    nome: "Achocolatado em Pó",
    descricao: "Achocolatado em Pó - 400g",
    unidadeMedida: "g",
    pesoUnitario: 400,
    categoria: "Bebidas",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "60",
    codigoProduto: "100049",
    nome: "Cereal Matinal Chocolate",
    descricao: "Cereal Matinal Chocolate - 250g",
    unidadeMedida: "g",
    pesoUnitario: 250,
    categoria: "Matinais",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: "61",
    codigoProduto: "100050",
    nome: "Granola Tradicional",
    descricao: "Granola Tradicional - 250g",
    unidadeMedida: "g",
    pesoUnitario: 250,
    categoria: "Matinais",
    temperaturaIdeal: "Ambiente",
    status: "Ativo"
  },
  {
    id: 'prod-001',
    codigoProduto: '12345',
    nome: 'Carne Bovina Picanha',
    descricao: 'Picanha bovina resfriada, corte especial.',
    unidadeMedida: 'KG',
    pesoUnitario: 1.2,
    categoria: 'Carnes',
    temperaturaIdeal: 'Resfriado',
    status: 'ativo',
  },
  {
    id: 'prod-002',
    codigoProduto: '67890',
    nome: 'Frango Congelado Inteiro',
    descricao: 'Frango inteiro congelado, sem miúdos.',
    unidadeMedida: 'UN',
    pesoUnitario: 2.5,
    categoria: 'Aves',
    temperaturaIdeal: 'Congelado',
    status: 'ativo',
  },
  {
    id: 'prod-003',
    codigoProduto: '11223',
    nome: 'Leite Integral UHT',
    descricao: 'Leite integral longa vida, 1 litro.',
    unidadeMedida: 'UN',
    pesoUnitario: 1.03,
    categoria: 'Laticínios',
    temperaturaIdeal: 'Seca',
    status: 'ativo',
  },
  {
    id: 'prod-004',
    codigoProduto: '44556',
    nome: 'Queijo Mussarela Fatiado',
    descricao: 'Queijo mussarela fatiado, 200g.',
    unidadeMedida: 'UN',
    pesoUnitario: 0.2,
    categoria: 'Laticínios',
    temperaturaIdeal: 'Resfriado',
    status: 'ativo',
  },
  {
    id: 'prod-005',
    codigoProduto: '77889',
    nome: 'Sorvete de Chocolate',
    descricao: 'Sorvete cremoso sabor chocolate, 2 litros.',
    unidadeMedida: 'UN',
    pesoUnitario: 1.1,
    categoria: 'Sobremesas',
    temperaturaIdeal: 'Congelado',
    status: 'ativo',
  },
  {
    id: 'prod-006',
    codigoProduto: '578150', // Código da imagem fornecida
    nome: 'Bisteca Suína Congelada',
    descricao: 'Bisteca suína congelada, corte especial para churrasco.',
    unidadeMedida: 'KG',
    pesoUnitario: 0.5,
    categoria: 'Carnes Suínas',
    temperaturaIdeal: 'Congelado',
    status: 'ativo',
  },
  {
    id: 'prod-007',
    codigoProduto: '98765',
    nome: 'Salsicha Hot Dog',
    descricao: 'Salsicha de frango e porco para hot dog, pacote 500g.',
    unidadeMedida: 'UN',
    pesoUnitario: 0.5,
    categoria: 'Embutidos',
    temperaturaIdeal: 'Resfriado',
    status: 'ativo',
  },
  {
    id: 'prod-008',
    codigoProduto: '23456',
    nome: 'Pão de Queijo Congelado',
    descricao: 'Pão de queijo congelado, pronto para assar, pacote 1kg.',
    unidadeMedida: 'UN',
    pesoUnitario: 1.0,
    categoria: 'Panificados',
    temperaturaIdeal: 'Congelado',
    status: 'ativo',
  },
  {
    id: 'prod-9741', // ID único para o novo produto
    codigoProduto: '9741',
    nome: 'Produto Exemplo 9741',
    descricao: 'Descrição do Produto Exemplo 9741',
    unidadeMedida: 'UN',
    pesoUnitario: 1.0,
    categoria: 'Categoria Exemplo',
    temperaturaIdeal: 'Ambiente',
    status: 'ativo',
  },
];
